// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3cMNy-32MyAo8KLCjE-swVkjTlX1mML4',
    appId: '1:643498475124:web:3017cbe862a8f403435b21',
    messagingSenderId: '643498475124',
    projectId: 'touchandlist',
    authDomain: 'touchandlist.firebaseapp.com',
    storageBucket: 'touchandlist.appspot.com',
    measurementId: 'G-92GR33JCCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9twEP7edoKBnDhfWtlHPrgw_txtUB9iI',
    appId: '1:643498475124:android:d7f999db0b47dfca435b21',
    messagingSenderId: '643498475124',
    projectId: 'touchandlist',
    storageBucket: 'touchandlist.appspot.com',
  );
}
